from jitcdde import y

# T_c_f1 = lambda tau=None: y(0, tau) if tau is not None else y(0)
# T_c_f2 = lambda tau=None: y(7, tau) if tau is not None else y(7)
# T_c_t1 = lambda tau=None: y(8, tau) if tau is not None else y(8)
# T_c_c1 = lambda tau=None: y(9, tau) if tau is not None else y(9)
# T_c_c2 = lambda tau=None: y(10, tau) if tau is not None else y(10)
# T_c_m = lambda tau=None: y(11, tau) if tau is not None else y(11)

# T_hx_fh1_f1 = lambda tau=None: y(12, tau) if tau is not None else y(12)
# T_hx_fh1_f2 = lambda tau=None: y(13, tau) if tau is not None else y(13)
# T_hx_fh1_t1 = lambda tau=None: y(14, tau) if tau is not None else y(14)
# T_hx_fh1_h1 = lambda tau=None: y(15, tau) if tau is not None else y(15)
# T_hx_fh1_h2 = lambda tau=None: y(16, tau) if tau is not None else y(16)

# T_hx_fh2_f1 = lambda tau=None: y(17, tau) if tau is not None else y(17)
# T_hx_fh2_f2 = lambda tau=None: y(18, tau) if tau is not None else y(18)
# T_hx_fh2_t1 = lambda tau=None: y(19, tau) if tau is not None else y(19)
# T_hx_fh2_h1 = lambda tau=None: y(20, tau) if tau is not None else y(20)
# T_hx_fh2_h2 = lambda tau=None: y(21, tau) if tau is not None else y(21)

# T_hx_ch1_c1 = lambda tau=None: y(22, tau) if tau is not None else y(22)
# T_hx_ch1_c2 = lambda tau=None: y(23, tau) if tau is not None else y(23)
# T_hx_ch1_t1 = lambda tau=None: y(24, tau) if tau is not None else y(24)
# T_hx_ch1_h1 = lambda tau=None: y(25, tau) if tau is not None else y(25)
# T_hx_ch1_h2 = lambda tau=None: y(26, tau) if tau is not None else y(26)

# T_hx_ch2_c1 = lambda tau=None: y(27, tau) if tau is not None else y(27)
# T_hx_ch2_c2 = lambda tau=None: y(28, tau) if tau is not None else y(28)
# T_hx_ch2_t1 = lambda tau=None: y(29, tau) if tau is not None else y(29)
# T_hx_ch2_h1 = lambda tau=None: y(30, tau) if tau is not None else y(30)
# T_hx_ch2_h2 = lambda tau=None: y(31, tau) if tau is not None else y(31)

# T_hx_hwf1_h1 = lambda tau=None: y(32, tau) if tau is not None else y(32)
# T_hx_hwf1_h2 = lambda tau=None: y(33, tau) if tau is not None else y(33)
# T_hx_hwf1_t1 = lambda tau=None: y(34, tau) if tau is not None else y(34)
# T_hx_hwf1_w1 = lambda tau=None: y(35, tau) if tau is not None else y(35)
# T_hx_hwf1_w2 = lambda tau=None: y(36, tau) if tau is not None else y(36)

# T_hx_hwf2_h1 = lambda tau=None: y(37, tau) if tau is not None else y(37)
# T_hx_hwf2_h2 = lambda tau=None: y(38, tau) if tau is not None else y(38)
# T_hx_hwf2_t1 = lambda tau=None: y(39, tau) if tau is not None else y(39)
# T_hx_hwf2_w1 = lambda tau=None: y(40, tau) if tau is not None else y(40)
# T_hx_hwf2_w2 = lambda tau=None: y(41, tau) if tau is not None else y(41)

# T_hx_hwc1_h1 = lambda tau=None: y(42, tau) if tau is not None else y(42)
# T_hx_hwc1_h2 = lambda tau=None: y(43, tau) if tau is not None else y(43)
# T_hx_hwc1_t1 = lambda tau=None: y(44, tau) if tau is not None else y(44)
# T_hx_hwc1_w1 = lambda tau=None: y(45, tau) if tau is not None else y(45)
# T_hx_hwc1_w2 = lambda tau=None: y(46, tau) if tau is not None else y(46)

# T_hx_hwc2_h1 = lambda tau=None: y(47, tau) if tau is not None else y(47)
# T_hx_hwc2_h2 = lambda tau=None: y(48, tau) if tau is not None else y(48)
# T_hx_hwc2_t1 = lambda tau=None: y(49, tau) if tau is not None else y(49)
# T_hx_hwc2_w1 = lambda tau=None: y(50, tau) if tau is not None else y(50)
# T_hx_hwc2_w2 = lambda tau=None: y(51, tau) if tau is not None else y(51)

# y_n = lambda tau=None: y(52, tau) if tau is not None else y(52)
# y_C1 = lambda tau=None: y(53, tau) if tau is not None else y(53)
# y_C2 = lambda tau=None: y(54, tau) if tau is not None else y(54)
# y_C3 = lambda tau=None: y(55, tau) if tau is not None else y(55)
# y_C4 = lambda tau=None: y(56, tau) if tau is not None else y(56)
# y_C5 = lambda tau=None: y(57, tau) if tau is not None else y(57)
# y_C6 = lambda tau=None: y(58, tau) if tau is not None else y(58)
# y_rho = lambda tau=None: y(59, tau) if tau is not None else y(59)

